foxp2projects/Symfony/src/foxp2/backofficeBundle/Entity/RecursiveCategoryIterator.php
<?php

namespace foxp2\backofficeBundle\Entity;

use foxp2\backofficeBundle\Entity\Categories;
use Doctrine\Common\Collections\Collection;

class RecursiveCategoryIterator implements \RecursiveIterator
{

    private $_data;

    public function __construct(Collection $data)
    {
        $this->_data = $data;
    }

    public function hasChildren()
    {
        return ( ! $this->_data->current()->getChildren()->isEmpty());
    }

    public function getChildren()
    {
        return new RecursiveCategoryIterator($this->_data->current()->getChildren());
    }

    public function current()
    {
        return $this->_data->current();
    }

    public function next()
    {
        $this->_data->next();
    }

    public function key()
    {
        return $this->_data->key();
    }

    public function valid()
    {
        return $this->_data->current() instanceof Categories;
    }

    public function rewind()
    {
        $this->_data->first();
    }
}
?>

foxp2projects/Symfony/src/foxp2/backofficeBundle/Form/CategoriesType.php
<?php

namespace foxp2\backofficeBundle\Form;

use foxp2\backofficeBundle\Entity\CategoriesRepository;
use foxp2\backofficeBundle\Form\EventListener\CategoriesDateSubscriber;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class CategoriesType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {        
        $builder            
            ->add('categoriesName','text',array('label'=>'Category name'))
            ->add('categoriesTitle','text',array('label' => 'Category title'))
            ->add('categoriesSubTitle', 'text', array('label' => 'Category sub title', 'required' => false))
            ->add('parentId','entity', array(
                  'class' => 'foxp2backofficeBundle:Categories',
                  'empty_value' => 'Please select ...',
                  'property' => 'categoriesName',
                  'query_builder' => function(CategoriesRepository $er){
                            return $er->getCategoriesList();                              
                  },                  
                  'required' => false,
                  'label' => 'Category parent',
                 
                 ))        
            ->add('categoriesDescription', 'ckeditor',array('label' => 'Category description'));
                 
        $builder->addEventSubscriber(new CategoriesDateSubscriber());
        
    }
   
     /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(            
            'data_class' => 'foxp2\backofficeBundle\Entity\Categories',             
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'foxp2_backofficeBundle_categoriestype';
    }
}

foxp2projects/Symfony/src/foxp2/backofficeBundle/Controller/CategoriesController.php
<?php
namespace foxp2\backofficeBundle\Controller;

use foxp2\backofficeBundle\Entity\Categories;
use foxp2\backofficeBundle\Form\CategoriesType;
use foxp2\backofficeBundle\Form\SearchType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * Categories controller.
 *
 */
class CategoriesController extends Controller {

    /**
     * Liste des catégories réordonnées
     *
     */
    public function indexAction($page) {

        $em = $this->getDoctrine()->getManager();

        $counter = $em->getRepository('foxp2backofficeBundle:Categories')->getCategoriesCount();

        $result_per_page = $this->container->getParameter('category_per_page');

        $number_of_page = ceil($counter / $result_per_page);

        $offset = ( $page - 1 ) * $result_per_page;

        if ($page < 1 or $page > $number_of_page && $counter != 0) {

            $this->get('session')->getFlashBag()->add('error', 'This page does not exist !');
            return $this->redirect($this->generateUrl('categories_index'));
        }

        $entities = $em->getRepository('foxp2backofficeBundle:Categories')->getAllCategoriesList($result_per_page, $offset);

        $form_search = $this->createForm(new SearchType());

        return $this->render('foxp2backofficeBundle:Categories:index.html.twig', array(
                    'keyword' => '',
                    'page' => $page,
                    'nb_pages' => $number_of_page,
                    'counter' => $offset,
                    'form_search' => $form_search->createView(),
                    'entities' => $entities,
        ));
    }

    /**
     * 
     * @param Request $request
     * @return type
     */
    public function searchAction(Request $request) {          

        $result_per_page = $this->container->getParameter('category_per_page');

        $em = $this->getDoctrine()->getManager();

        $request = $this->container->get('request');

        $form_search = $this->createForm(new SearchType());

        $form_search->submit($request);

        if ($request->getMethod() == 'POST') {
            $keyword = $request->request->get("search");

            $entity = $em->getRepository('foxp2backofficeBundle:Categories')->findCategoryByName(trim($keyword));

            if ($entity) {

                $result = sizeof($entity);

                if ($result > 1) {

                    $number_of_page = ceil($result / $result_per_page);
                    
                    $this->get('session')->getFlashBag()->add('message', 'Research with %s has returned %s results');
                    $this->get('session')->getFlashBag()->add('keyword', $keyword);
                    $this->get('session')->getFlashBag()->add('result', $result);

                    return $this->render('foxp2backofficeBundle:Categories:index.html.twig', array(
                                'page' => 1,
                                'counter' => $result,
                                'nb_pages' => $number_of_page,
                                'keyword' => $keyword,
                                'form_search' => $form_search->createView(),
                                'entities' => $entity,
                    ));
                } else { 
                    
                    $aloneentity = $em->getRepository('foxp2backofficeBundle:Categories')->find($entity[0]->getId());
                     
                    $deleteForm = $this->createDeleteForm($entity[0]->getId());
                    
                    $this->get('session')->getFlashBag()->add('message', 'Research with %s only returned this result');
                    $this->get('session')->getFlashBag()->add('keyword', $keyword);

                    return $this->render('foxp2backofficeBundle:Categories:show.html.twig', array(                                
                                'entity' => $aloneentity,
                                'delete_form' => $deleteForm->createView(),
                    ));
                }
            } else {

                 $this->get('session')->getFlashBag()->add('error', 'Research with %s did not return any results');
                 $this->get('session')->getFlashBag()->add('keyword', $keyword);

                return $this->redirect($this->generateUrl('categories_index'));
            }
        }
    }

    /**
     * Creates a new Categories entity.
     *
     */
    public function createAction(Request $request) {
        
       if (false === $this->get('security.context')->isGranted('ROLE_SUPER_ADMIN')) {

            $this->get('session')->getFlashBag()->add('error', 'This action requires administrator rights !');
            return $this->redirect($this->generateUrl('categories_index'));
        } else {
        
        $entity = new Categories();

        $em = $this->getDoctrine()->getManager();      

        $form = $this->createForm(new CategoriesType(), $entity);

        $form->submit($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();
            
            $this->get('session')->getFlashBag()->add('message', 'Category %s was successfully created');
            $this->get('session')->getFlashBag()->add('keyword', $entity->getCategoriesName()); 
            
            return $this->redirect($this->generateUrl('categories_show', array('id' => $entity->getId())));
        }
        return $this->render('foxp2backofficeBundle:Categories:new.html.twig', array(
                    'entity' => $entity,
                    'new_form' => $form->createView(),
        ));
        }
    }

    /**
     * Displays a form to create a new Categories entity.
     *
     */
    public function newAction() {
        
        $entity = new Categories();

        $form = $this->createForm(new CategoriesType(), $entity);

        return $this->render('foxp2backofficeBundle:Categories:new.html.twig', array(
                    'entity' => $entity,
                    'new_form' => $form->createView(),
        ));
    }

    /**
     * 
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function ajaxshowAction() {

        $request = $this->getRequest();

        $em = $this->getDoctrine()->getManager();

        if ($request->isXmlHttpRequest()) {            

            $id = $request->request->get('id');

            $entity = $em->getRepository('foxp2backofficeBundle:Categories')->ajaxCategoryByid($id);

            if ($entity) {

                foreach ($entity as $key) {

                    $data[] = array(
                        'id_category' => $key->getId(),
                        // donnée optionnelle
                        'parent_id_category' => ($key->getParentId() !== null ) ? $key->getParentId()->__tostring() : '',
                        'category_name' => $key->getCategoriesName(),
                        'category_title' => $key->getcategoriesTitle(),
                        // donnée optionnelle
                        'category_sub_title' => ($key->getcategoriesSubTitle() !== null) ? $key->getcategoriesSubTitle() : '',
                        'created_at' => $key->getDateCreated()->format('d-m-Y'),
                        // donnée optionnelle
                        'updated_at' => ($key->getDateModified() !== null) ? $key->getDateModified()->format('d-m-Y') : '' 
                    );
                }

                $response = new Response(json_encode($data));

                $response->headers->set('Content-Type', 'application/json');

                return $response;
            }
        }
    }

    /**
     * 
     * @param type $id
     * @return Categories entity
     */
    public function showAction($id) {   
        

        $em = $this->getDoctrine()->getManager();    

        $entity = $em->getRepository('foxp2backofficeBundle:Categories')->find($id);    
        
        if (!$entity) {
            $this->get('session')->getFlashBag()->add('error', 'This category does not exist');
            return $this->redirect($this->generateUrl('categories_index'));
        }

        $deleteForm = $this->createDeleteForm($id);

        return $this->render('foxp2backofficeBundle:Categories:show.html.twig', array(
                    'entity' => $entity,
                    'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing Categories entity.
     *
     */
    public function editAction($id) {
        
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('foxp2backofficeBundle:Categories')->find($id);

        if (!$entity) {
            $this->get('session')->getFlashBag()->add('error', 'This category does not exist');
            return $this->redirect($this->generateUrl('categories_index'));
        }
        $editForm = $this->createForm(new CategoriesType(), $entity);
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('foxp2backofficeBundle:Categories:edit.html.twig', array(
                    'entity' => $entity,
                    'edit_form' => $editForm->createView(),
                    'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Edits an existing Categories entity.
     *
     */
    public function updateAction(Request $request, $id) {
        
       if (false === $this->get('security.context')->isGranted('ROLE_SUPER_ADMIN')) {

            $this->get('session')->getFlashBag()->add('error', 'This action requires administrator rights !');
            return $this->redirect($this->generateUrl('categories_index'));
        } else {        
        
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('foxp2backofficeBundle:Categories')->find($id);

        if (!$entity) {

foxp2projects/Symfony/src/foxp2/backofficeBundle/Resources/views/Categories/edit.html.twig
{# \Symfony\src\foxp2\backofficeBundle\Resources\views\Categories\edit.html.twig #}
{% extends "foxp2backofficeBundle:Common:layout_admin.html.twig" %}
{% form_theme edit_form  'foxp2backofficeBundle:Form:fields.html.twig' %}
{% block application -%}
        <div id="nav-bar">
            <div class="row">
                <div class="span9">
                    <div id="header-container">
                        <a id="backbutton" class="win-backbutton" style="margin-right: 10px;" href="{{ path('categories_index') }}"></a>
                        <div class="dropdown pull-right">
                            <h1 class="header-dropdown">{{ 'Edit a category'|trans }}</h1>
                        </div>
                    </div>
                </div>
                {% include "foxp2backofficeBundle:Secured:logout.html.twig" %}
            </div>
        </div>
<div class="row-fluid">
{% set flashbag_messages = app.session.flashbag.get('message') %}
{% if flashbag_messages is not empty %}  
<div class="clearfix"></div>
<div class="alert alert-danger">
<button type="button" class="close" data-dismiss="alert"></button>   
    {% for message in flashbag_messages %}
            <strong>{{ message|trans|raw }}</strong>
    {% endfor %}
</div>
{% endif %}   
    <form style="margin-bottom:93px;" id="categories_update" action="{{ path('categories_update', { 'id': entity.id }) }}" method="post" {{ form_enctype(edit_form) }}>
        <input type="hidden" name="_method" value="PUT" />        
        {{ form_widget(edit_form) }}
    </form>
   
<!-- app bar -->
<div id="app-bar" class="win-commandlayout win-ui-dark">
    <a class="win-command orange" href="{{ path('categories_index') }}">
        <span class="win-commandicon win-commandring icon-list icon-fox"></span>   
        <span class="win-label orange">{{ 'List of categories'|trans }}</span>
    </a>
    <a title="" id="button_submit" class="win-command blue pull-right" href="#">
        <span class="win-commandicon win-commandring icon-pen-2"></span>   
        <span class="win-label blue">{{ 'Edit'|trans }}</span>
    </a>
</div>
<script>
jQuery('#app-bar').animate({'bottom': '+0px'},400);
$('#button_submit').click(function() {
  $('#categories_update').submit();
}); 
</script>
</div>
{% endblock %}

foxp2projects/Symfony/src/foxp2/backofficeBundle/Resources/views/Categories/keyboard.html.twig
{# \Symfony\src\foxp2\backofficeBundle\Resources\views\Categories\keyboard.html.twig #}
<div id="keyboard" class="modal message hide fade">    
    <div class="modal-header">        
    <h1 class="text-info"><strong>Gestion des actions avec le clavier</strong></h1>
    <br />
    <p class="well"><strong>Afin d'améliorer votre expérience sur cette interface, des raccourcis clavier, décrits ci-dessous, ont été ajoutés pour accéder aux différentes actions possibles sur cette page.</strong></p>
    </div>
    <div class="modal-body">
        
         <div class="listview-item bg-color-darken span6">
            <div class="pull-left" href="#">
               <img src="{{ asset("bundles/foxp2projects/images/letter_a.png") }}" style="width: 60px; height: 60px;" alt="letter-a" class="listview-item-object" data-src="holder.js/60x60">
            </div>
            <div class="listview-item-body">
                <h4 class="listview-item-heading"><strong>Ajouter une catégorie</strong></h4>
               <p class="two-lines">Cliquer sur la lettre a de votre clavier</p>
           </div>
         </div>
         <div class="listview-item bg-color-darken span6">
            <div class="pull-left" href="#">
               <img src="{{ asset("bundles/foxp2projects/images/letter_v.png") }}" style="width: 60px; height: 60px;" alt="letter-v" class="listview-item-object" data-src="holder.js/60x60">
            </div>
            <div class="listview-item-body">
                <h4 class="listview-item-heading"><strong>Voir une catégorie</strong></h4>
               <p class="two-lines">Après selection dans le tableau, cliquer sur la lettre v.</p>
           </div>
         </div>        
         <div class="listview-item bg-color-darken span6" style="margin-left: 0px;">
            <div class="pull-left" href="#">
               <img src="{{ asset("bundles/foxp2projects/images/letter_e.png") }}" style="width: 60px; height: 60px;" alt="letter-e" class="listview-item-object" data-src="holder.js/60x60">
            </div>
            <div class="listview-item-body">
                <h4 class="listview-item-heading"><strong>Editer une catégorie</strong></h4>
               <p class="two-lines">Après selection dans le tableau, cliquer sur la lettre e.</p>
           </div>
         </div>
         <div class="listview-item bg-color-darken span6">
            <div class="pull-left" href="#">
               <img src="{{ asset("bundles/foxp2projects/images/letter_i.png") }}" style="width: 60px; height: 60px;" alt="letter-i" class="listview-item-object" data-src="holder.js/60x60">
            </div>
            <div class="listview-item-body">
                <h4 class="listview-item-heading"><strong>Détails d'une catégorie</strong></h4>
               <p class="two-lines">Après selection dans le tableau, cliquer sur la lettre i pour voir les détails.</p>
           </div>
         </div> 
        <div class="modal-footer pull-right" style="margin-right: -15px">
            <button type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true"><i class="icon-cross"></i> Fermer</button>      
       </div>
    </div>
</div>

foxp2projects/Symfony/src/foxp2/backofficeBundle/Resources/views/Categories/new.html.twig
{# \Symfony\src\foxp2\projectsBundle\Resources\views\Categories\new.html.twig #}
{% extends "foxp2backofficeBundle:Common:layout_admin.html.twig" %}
{% form_theme new_form  'foxp2backofficeBundle:Form:fields.html.twig' %}
{% block application -%}
        <div id="nav-bar">
            <div class="row">
                <div class="span9">
                    <div id="header-container">
                        <a id="backbutton" class="win-backbutton" style="margin-right: 10px;" href="{{ path('categories_index') }}"></a>
                        <div class="dropdown pull-right">
                            <h1 class="header-dropdown">{{ 'Create a category'|trans }}</h1>
                        </div>
                    </div>
                </div>
                {% include "foxp2backofficeBundle:Secured:logout.html.twig" %}
            </div>
        </div>
<div class="row-fluid">
{% set flashbag_messages = app.session.flashbag.get('message') %}
{% if flashbag_messages is not empty %}        
<div class="alert alert-danger span5">
<button type="button" class="close" data-dismiss="alert"></button>   
    {% for message in flashbag_messages %}
            <strong>{{ message|trans|raw }}</strong>
    {% endfor %}
</div>
{% endif %}       
    <form style="margin-bottom:93px;" id="categories_create" action="{{ path('categories_create') }}" method="post" {{ form_enctype(new_form) }}>       
     {{ form_widget(new_form)}}           
    </form>

<!-- app bar -->
<div id="app-bar" class="win-commandlayout win-ui-dark">
    <a class="win-command orange" href="{{ path('categories_index') }}">
        <span class="win-commandicon win-commandring icon-list icon-fox"></span>   
        <span class="win-label orange">{{ 'List of categories'|trans }}</span>
    </a>
    <a title="" id="button_submit" class="win-command white pull-right" href="#">
        <span class="win-commandicon win-commandring icon-plus"></span>   
        <span class="win-label white">{{ 'Create'|trans }}</span>
    </a>
</div>
<script>
jQuery('#app-bar').animate({'bottom': '+0px'},400);
$('#button_submit').click(function() {
  $('#categories_create').submit();
}); 
</script>
</div>
{% endblock %}

foxp2projects/Symfony/src/foxp2/backofficeBundle/Resources/views/Categories/show.html.twig
{# \Symfony\src\foxp2\backofficeBundle\Resources\views\Categories\show.html.twig #}
{% extends "foxp2backofficeBundle:Common:layout_admin.html.twig" %}
{% block application -%}
        <div id="nav-bar">
            <div class="row">
                <div class="span9">
                    <div id="header-container">
                        <a id="backbutton" class="win-backbutton" style="margin-right: 10px;" href="{{ path('categories_index',{'page':1}) }}"></a>
                        <div class="dropdown pull-right">
                            <h1 class="header-dropdown">{{ 'See a category'|trans }}</h1>
                        </div>
                    </div>
                </div>
                {% include "foxp2backofficeBundle:Secured:logout.html.twig" %}
            </div>
        </div>
<div class="row-fluid">
{% set flashbag_messages = app.session.flashbag.get('message') %}
{% if flashbag_messages is not empty %}        
    <div id="alerts-container">    
    <div class="toast fade in">
        <button type="button" class="close" data-dismiss="alert" type="button"></button>
        <div class="pull-left">
            <img class="toast-object"  style="width: 90px; height: 90px;" 
                 src="{{ asset("bundles/foxp2projects/images/foxp2-90-90.png") }}" />
        </div>
    <div class="toast-body">
        <h4 class="toast-heading">{{ 'Message of application'|trans }}</h4>
        <p>
    {% for message in flashbag_messages %}
            <strong>{{ message|trans|raw }}</strong>
    {% endfor %}
        </p>
    </div>
    </div>
    </div>
{% endif %}
    <table class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>Id catégorie</th>
                <th style="text-align: center;">{{ 'Category name'|trans }}</th>                
                <th style="text-align: center;">{{ 'Created at'|trans }}</th>
                <th style="text-align: center;">{{ 'Updated at'|trans }}</th>
                {% if entity.parentId %}               
                <th style="text-align: center;">{{ 'Category parent'|trans }}</th>
                <th style="text-align: right;">{{ 'Action'|trans }}</th>
                {% endif %}
            </tr>
        </thead>
        <tbody class="listcategories">
            <tr id="{{ entity.id }}" data-category="{{ entity.id }}">                
                <td>{{ entity.id }}</td>
                <td style="text-align: center;">{{ entity.categoriesName }}</td>                                      
                <td style="text-align: center;">{{ entity.dateCreated|date('d-m-Y') }}</td>                      
                <td style="text-align: center;">{{ entity.dateModified|date('d-m-Y') }}</td>
                {% if entity.parentId %}                
                <td style="text-align: center;">{% if entity.parentId %}{{ entity.parentId.categoriesName }}{% endif %}</td>
                <td style="text-align: right;">
                {% if entity.parentId %}
                        <div class="btn-group">
                        <a class="btn btn-info" href="{{ path('categories_edit',{'id' : entity.parentId}) }}">éditer</a>
                        <a class="btn btn-primary" href="{{ path('categories_show',{'id' : entity.parentId}) }}">voir</a>
                {% endif %}
                </td>  
                {% endif %}
            </tr>
            <tr>
                <th style="text-align: center;">{{ 'Title'|trans }} :</th>
                <td colspan="{% if entity.parentId %}2{% else %}1{% endif %}">{{ entity.categoriesTitle }}</td>
                <th style="text-align: center;">{{ 'Sub title'|trans }} :</th>
                <td colspan="{% if entity.parentId %}3{% else %}1{% endif %}">{{ entity.categoriesSubTitle }}</td>
            </tr>
            <tr>
                <th style="text-align: center;vertical-align: middle;">{{ 'Description'|trans }} :</th>
                <td colspan="{% if entity.parentId %}5{% else %}4{% endif %}">{{ entity.categoriesDescription|raw }}</td>
            </tr>
        </tbody>
    </table>
    {% if entity.children|length > 0 %}
    <h2>{{ 'List of children category'|trans }} : <small>{{ entity.children|length }} {{ 'Sub category'|trans }}{% if entity.children|length > 1 %}s{% endif %}</small></h2><hr>
    <table class="table table-bordered table-hover table-striped">    
        <thead>
            <tr>
                <th>{{ 'Id of sub category'|trans }}</th>
                <th style="text-align: center;">{{ 'Name of children category'|trans }}</th>
                <th style="text-align: right;">{{ 'Action'|trans }}</th>
            </tr>
        </thead>
        <tbody>
    {% for category in entity.children %}
            <tr>
                <td>{{ category.id }}</td>
                <td style="text-align: center;">{{ category.categoriesName }}</td>
                <td style="text-align: right;">
                    <div class="btn-group">
                    <a class="btn btn-info" href="{{ path('categories_edit',{'id' : category.id}) }}"><strong>{{ 'Edit'|trans }}</strong></a>
                    <a class="btn btn-primary" href="{{ path('categories_show',{'id' : category.id}) }}"><strong>{{ 'See'|trans }}</strong></a>
                    </div>
                </td>
            </tr>
    {% endfor %}
        </tbody>
    </table> 
    {% endif %}
    {% if entity.articles|length > 0 %}
    <h2>{{ 'List of articles'|trans }} : <small>{{ entity.articles|length }} {{ 'article'|trans }}{% if entity.articles|length > 1 %}s{% endif %}</small></h2><hr>
    <table class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>{{ 'id article'|trans }}</th>
                <th style="text-align: center;">{{ 'Article Name'|trans }}</th>
                <th style="text-align: right;">{{ 'Action'|trans }}</th>
            </tr>
        </thead>
        <tbody>
        {% for article in entity.articles %}
            <tr>
            <td>{{ article.id }}</a></td>
            <td>{{ article.articleName }}</td>
            <td style="text-align: right;">
                <div class="btn-group">
                    <a class="btn btn-info" href="{{ path('articles_edit',{'id' : article.id}) }}"><strong>{{ 'Edit'|trans }}</strong></a>
                <a class="btn btn-primary" href="{{ path('articles_show',{'id' : article.id}) }}"><strong>{{ 'See'|trans }}</strong></a>
                </div>
            </td>
            </tr>
        {% endfor %}
         </tbody>
    </table>
    {% endif %}
    <form id="delete_categories" action="{{ path('categories_delete', { 'id': entity.id }) }}" method="post">
    <input type="hidden" name="_method" value="DELETE" />
    {{ form_widget(delete_form) }}   
    </form>
<!-- app bar -->
<div id="app-bar" class="win-commandlayout win-ui-dark">
    <a class="win-command orange" href="{{ path('categories_index', {'page':1}) }}">
        <span class="win-commandicon win-commandring icon-list icon-fox"></span>   
        <span class="win-label orange">{{ 'List of categories'|trans }}</span>
    </a>
    <a title="" id="button_submit" class="win-command red pull-right" href="#">
        <span class="win-commandicon win-commandring icon-delete"></span>   
        <span class="win-label red">{{ 'Delete'|trans }}</span>
    </a>
    <a class="win-command white pull-right" href="{{ path('categories_edit', { 'id': entity.id }) }}">
        <span class="win-commandicon win-commandring icon-pencil-2"></span>   
        <span class="win-label white">{{ 'Edit'|trans }}</span>
    </a>
</div>
<script>
jQuery('#app-bar').animate({'bottom': '+0px'},400);  
$('#button_submit').click(function() {
  $('#delete_categories').submit();
}); 
</script>
</div>
{% endblock %}